/**
 * @author     Dmytro
 * @published  June 09 2024
 * @decription The definition for Chat function
 */
module.exports = {
  TIMEOUT_MINS: 15,
  CONNECTION: "connection",
  DISCONNECT: "disconnect",
  EXPIRED: "expired",
  NEW_USER: "new user",
  USER_OUT: "user out",
  USER_REGISTER: "user register",
  GET_USERS: "get users",
  GET_RECENT_USERS: "get recent users",
  GET_FRIEND_USERS: "get friend users",
  GET_SEARCH_USERS: "get search users",
  ADD_FRIEND: "add friend",
  GET_MY_GROUPS: "get my groups",
  GET_FAV_GROUPS: "get fav groups",
  USER_LOGGED: "user logged",
  USER_LOGGED_AS_ANNON: "user logged as annon",
  USER_LOGGED_WILD_SUB: "user logged wild sub",
  SEND_MSG: "send msg",
  SEND_GROUP_MSG: "send group msg",
  SEND_GROUP_MSG_ANON: "send group msg anon",
  GET_MSG: "get msg",
  GET_GROUP_MSG: "get group msg",
  LISTEN_GROUP_MSG: "listen group msg",
  GET_HISTORY: "get history",
  GET_GROUP_HISTORY: "get group history",
  GET_GROUP_HISTORY_ANON: "get group history anon",
  SEND_USERS: "send users",
  LOGGED_NEW_USER: "logged new user",
  REFRESH: "refresh",
  READ_MSG: "read msg",
  READ_GROUP_MSG: "read group msg",
  DELETE_GROUP_MSG: "delete group msg",
  BAN_GROUP_USER: "ban group user",
  UNBAN_GROUP_USER: "unban group user",
  UNBAN_GROUP_USERS: "unban group users",
  ADD_LISTENER_GROUP: "add listener to group",
  UNREAD: "unread",
  FORBIDDEN: "forbidden",
  ALL_REFRESH: "allRefresh",
  SERVER_ERROR: "server error",
  JOIN_TO_GROUP: "join to group",
  DELETE_MSG: "delete msg",
  UPDATE_FAV_GROUPS: "update fav groups",
  GROUP_UPDATED: "group updated",
  UPDATE_CHAT_RULES: "update chat rules",
  GET_CHAT_RULES: "get chat rules",
  UPDATE_CENSORED_CONTENTS: "update censored contents",
  UPDATE_GROUP_MODERATORS: "update group moderators",
  CLEAR_GROUP_CHAT: "clear group chat",
  PIN_MESSAGE: "pin message",
  UNPIN_MESSAGE: "unpin message",
  GET_PINNED_MESSAGES: "get pinned messages",
  UPDATE_GROUP_POST_LEVEL: "udpate group post level",
  UPDATE_MOD_PERMISSIONS: "update mod permissions",
  SEND_GROUP_NOTIFY: "send group notify",
  UPDATE_GROUP_CHATBOX_STYLE: "udpate group chatbox style",
  TIMEOUT_USER: "timout user",
  GET_BLOCKED_USERS_INFO: "get blocked users info",
  BLOCK_USER: "block user",
  UNBLOCK_USER: "unblock user",
  GET_GROUP_ONLINE_USERS: "get group online users"
}