/*
 Navicat Premium Data Transfer

 Source Server         : localhost_5432
 Source Server Type    : PostgreSQL
 Source Server Version : 160001 (160001)
 Source Host           : localhost:5432
 Source Catalog        : Chatgram
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 160001 (160001)
 File Encoding         : 65001

 Date: 08/06/2024 00:39:35
*/

-- ----------------------------
-- Sequence structure for Messages_Id_seq
-- ----------------------------
CREATE SEQUENCE IF NOT EXISTS "public"."Profession_Id_seq";

-- ----------------------------
-- Table structure for Profession
-- ----------------------------
DROP TABLE IF EXISTS "public"."Profession";
CREATE TABLE "public"."Profession" (
  "Id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 7
CACHE 1
),
  "Profession" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "Role" int2 NOT NULL DEFAULT 0
)
;

-- ----------------------------
-- Records of Profession
-- ----------------------------
INSERT INTO "public"."Profession" VALUES (1, 'Web Developer', 0);
INSERT INTO "public"."Profession" VALUES (2, 'Wedding Planner', 0);
INSERT INTO "public"."Profession" VALUES (3, 'Event Manager', 0);
INSERT INTO "public"."Profession" VALUES (4, 'Fashion Manager', 0);
INSERT INTO "public"."Profession" VALUES (5, 'Clothing', 0);
INSERT INTO "public"."Profession" VALUES (6, 'Mechanic', 0);
INSERT INTO "public"."Profession" VALUES (8, 'PM', 1);
INSERT INTO "public"."Profession" VALUES (9, 'CTO', 1);
INSERT INTO "public"."Profession" VALUES (7, 'CEO', 1);
INSERT INTO "public"."Profession" VALUES (10, 'CFO', 1);
INSERT INTO "public"."Profession" VALUES (12, 'Recruiter', 1);
INSERT INTO "public"."Profession" VALUES (11, 'Invester', 1);
INSERT INTO "public"."Profession" VALUES (13, 'Receptionist', 1);
INSERT INTO "public"."Profession" VALUES (14, 'HR Manager', 1);

-- ----------------------------
-- Auto increment value for Profession
-- ----------------------------
SELECT setval('"public"."Profession_Id_seq"', 14, true);

-- ----------------------------
-- Primary Key structure for table Profession
-- ----------------------------
ALTER TABLE "public"."Profession" ADD CONSTRAINT "Products_pkey" PRIMARY KEY ("Id");
